development:
  host: localhost
  database: loop_development

test:
  host: localhost
  database: loop_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
